### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gubo** [mgechev/cli-builders-demo#9]
trying to run the builder:

_**ng run builder-test:touch**_
An unhandled exception occurred: Cannot find module '/temp/cli-builders-demo/command-builder/command'

then package.json change:
"implementation": "./command/index.ts",

_**ng run builder-test:touch**_

```
[error] /temp/cli-builders-demo/command-builder/command/index.ts:1
import { BuilderOutput, createBuilder } from '@angular-devkit/architect';
^^^^^^

SyntaxError: **Cannot use import statement outside a module**
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /temp/cli-builders-demo/builder-test/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:113:61
    at async WorkspaceNodeModulesArchitectHost.loadBuilder (/temp/cli-builders-demo/builder-test/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:113:26)

```

Angular CLI: 9.1.7
Node: 12.13.0
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

node -v
v12.13.0

**Comment by mgechev** [comment]
Looks like you need to build the builder first. You should point to a JavaScript, not a TypeScript file.
